export const getProductsList = () => {
    return [
        {
            id: 0,
            img_url: "https://falabella.scene7.com/is/image/Falabella/15911103_1?wid=240&hei=240&qlt=70",
            name: "Polo corte alto",
            price: "45,5",
            hasDiscount: true,
            price_discount: "40",
            currency: "€",
            discount_percentage: "10",
            more_colors_available: true,
        },
        {
            id: 1,
            img_url: "https://falabella.scene7.com/is/image/Falabella/110209989_1?wid=240&hei=240&qlt=70",
            name: "Sweater",
            price: "12,5",
            hasDiscount: false,
            price_discount: "12,5",
            currency: "€",
            discount_percentage: null,
            more_colors_available: true,
        },
        {
            id: 2,
            img_url: "https://falabella.scene7.com/is/image/Falabella/110209981_1?wid=240&hei=240&qlt=70",
            name: "Tshirt",
            price: "99,5",
            hasDiscount: true,
            price_discount: "90,5",
            currency: "€",
            discount_percentage: "10",
            more_colors_available: false,
        },
        {
            id: 4,
            img_url: "https://falabella.scene7.com/is/image/Falabella/110214525_1?wid=240&hei=240&qlt=70",
            name: "Sweater 11",
            price: "50,5",
            hasDiscount: true,
            price_discount: "45,5",
            currency: "€",
            discount_percentage: "10",
            more_colors_available: false,
        },
        {
            id: 5,
            img_url: "https://falabella.scene7.com/is/image/Falabella/110214465_1?wid=240&hei=240&qlt=70",
            name: "Poleron 5",
            price: "33,5",
            hasDiscount: false,
            price_discount: "33,5",
            currency: "€",
            discount_percentage: null,
            more_colors_available: true,
        },
        {
            id: 6,
            img_url: "https://falabella.scene7.com/is/image/Falabella/110214475_1?wid=240&hei=240&qlt=70",
            name: "TShirt 4",
            price: "25,5",
            hasDiscount: true,
            price_discount: "23,1",
            currency: "€",
            discount_percentage: "10",
            more_colors_available: false,
        },
        {
            id: 7,
            img_url: "https://falabella.scene7.com/is/image/Falabella/110214380?wid=240&hei=240&qlt=70",
            name: "Sweater 3",
            price: "25,5",
            hasDiscount: false,
            price_discount: "23,5",
            currency: "€",
            discount_percentage: null,
            more_colors_available: false,
        },
        {
            id: 8,
            img_url: "https://falabella.scene7.com/is/image/Falabella/110210131_1?wid=240&hei=240&qlt=70",
            name: "TShirt 2",
            price: "10,5",
            hasDiscount: false,
            price_discount: "10,5",
            currency: "€",
            more_colors_available: false,
            discount_percentage: null,
        }
    ];
};
